export const FETCH_DATA_SUCCEEDED = 'FETCH_DATA_SUCCEEDED';
export const FETCH_DATA_ERRORED = 'FETCH_DATA_ERRORED';
export const CLEAR_STATE = 'CLEAR_STATE';
export const PAGE_CHANGE = 'PAGE_CHANGE';
